logging:
  level.de.darkatra: info
  file: ${user.home}\AppData\Roaming\.patcher\launcher.log
patcherConfig:
  serverUrl: https://darkatra.de
  patchFilesFolderPath: bfmemod
  updaterJarName: Patcher.jar
  patcherUserDir: ${user.home}\AppData\Roaming\.bfme2rotwkPatcher\
---
logging:
  level.de.darkatra: debug
spring:
  profiles: dev