logging:
  level.de.darkatra: info
  file: ${user.home}\AppData\Roaming\.patcher\launcher.log
launcherConfig:
  serverUrl: https://darkatra.de
  patcherFilePath: bfmemod/Patcher.jar
  patcherUserDir: ${user.home}\AppData\Roaming\.bfme2rotwkPatcher\
---
logging:
  level.de.darkatra: debug
spring:
  profiles: dev