logging:
  level.de.darkatra: info

patcherConfig:
  serverUrl: https://darkatra.de
  patchFilesFolderPath: bfmemod
  patchListPath: bfmemod/version.txt
---
logging:
  level.de.darkatra: debug
spring:
  profiles: dev