logging:
  level.de.darkatra: info
  file: ${user.home}\AppData\Roaming\.patcher\updater.log
patcherConfig:
  serverUrl: https://darkatra.de
  patchFilesFolderPath: bfmemod
  patchListPath: bfmemod/version.txt
---
logging:
  level.de.darkatra: debug
spring:
  profiles: dev