logging:
  level.de.darkatra: info
  file: ${user.home}\AppData\Roaming\.patcher\updater.log
patcherConfig:
  serverUrl: https://darkatra.de
  patchFilesFolderPath: bfmemod
  updaterJarName: Patcher.jar
  patchListPath: bfmemod/version.txt
  patcherUserDir: ${user.home}\AppData\Roaming\.bfme2rotwkPatcher\
  configFilePath: ${patcherUserDir}\config.json
---
logging:
  level.de.darkatra: debug
spring:
  profiles: dev