spring:
  main:
    banner-mode: off

logging:
  file:
    name: ${user.home}/AppData/Roaming/.patcher/updater.log
  level:
    de.darkatra: info

updater-properties:
  base-url: https://darkatra.de
  patch-list-url: ${updater-properties.base-url}/bfmemod2/version.json
  updater-resolution:
    width: 800
    height: 600
  game-resolutions:
    - width: 1920
      height: 1080
  version: @version@
---
spring:
  profiles: dev

logging:
  level:
    de.darkatra: debug
