logging:
  file:
    name: ${user.home}\AppData\Roaming\.patcher\updater.log
  level:
    de.darkatra: info

updater-properties:
  server-url: https://darkatra.de
  patch-files-folder-url: ${updater-properties.server-url}/bfmemod
  patch-list-url: ${updater-properties.patch-files-folder-url}/version.txt
  updater-jar-name: updater.jar
  patcher-user-dir: ${user.home}\AppData\Roaming\.bfme2rotwkPatcher\
  config-file-path: ${updater-properties.patcher-user-dir}\config.json

---
spring:
  profiles: dev

logging:
  level.de.darkatra: debug
