logging:
  file:
    name: ${user.home}\AppData\Roaming\.patcher\updater.log
  level:
    de.darkatra: info

updater-properties:
  server-url: https://darkatra.de
  patch-files-folder-url: ${updater-properties.server-url}/bfmemod
  patch-list-url: ${updater-properties.patch-files-folder-url}/version.txt
  updater-jar-name: updater.jar
  patcher-user-folder-url: file://${user.home}\AppData\Roaming\.bfme2rotwkPatcher\
  patcher-resolution:
    width: 800
    height: 600
  game-resolutions:
    - width: 1920
      height: 1080

---
spring:
  profiles: dev

logging:
  level:
    de.darkatra: debug
