logging:
  level.de.darkatra: info
  file:
    name: ${user.home}\AppData\Roaming\.patcher\updater-builder.log
---
logging:
  level.de.darkatra: debug
spring:
  profiles: dev
patcher-config:
  server-url: http://localhost
