spring:
  main:
    banner-mode: off

logging:
  file:
    name: ${user.home}/AppData/Roaming/.patcher/updater-builder.log
  level:
    de.darkatra: info

update-builder-properties:
  base-url: https://darkatra.de
  version: @version@
---
spring:
  profiles: dev

logging:
  level:
    de.darkatra: debug
